version: "3.8"

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
